name: CI/CD Build

on:
  push:
    branches:
    - 'main'
    - 'release/**'
    tags:
    # [ok]   v1.0.0
    # [ok]   v1.2.3-20221212+s4c56d465
    # [fail] v1.2.3fail
    # [fail] v1.0
    # [fail] v1
    # [fail] 1.0.0
    # [fail] 1.0
    # [fail] 1
    - ^v([0-9]+.[0-9]+.[0-9])(\-.*)*$

jobs:
  print:
    runs-on: ubuntu-22.04
    steps:
    - name: Imprime variáveis de ambiente
      run: env
  version:
    runs-on: ubuntu-22.04
    outputs:
      var1: ${{ 'variavel 1' }}
      var2: ${{ 'variavel 2' }}
      var3: ${{ 'variável 3' }}
      version: ${{ steps.get_version.outputs.version }}
      version-without-v: ${{ steps.get_version.outputs.version-without-v }}
      is-semver: ${{ steps.get_version.outputs.is-semver }}
      major: ${{ steps.get_version.outputs.major }}
      minor: ${{ steps.get_version.outputs.minor }}
      patch: ${{ steps.get_version.outputs.patch }}
      prerelease: ${{ steps.get_version.outputs.prerelease }}
      build: ${{ steps.get_version.outputs.build }}
    steps:
    - name: Define variáveis
      run: echo 'Definindo variáveis...'

  get-version:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      version-without-v: ${{ steps.get_version.outputs.version-without-v }}
      is-semver: ${{ steps.get_version.outputs.is-semver }}
      major: ${{ steps.get_version.outputs.major }}
      minor: ${{ steps.get_version.outputs.minor }}
      patch: ${{ steps.get_version.outputs.patch }}
      prerelease: ${{ steps.get_version.outputs.prerelease }}
      build: ${{ steps.get_version.outputs.build }}
    steps:
    - name: Get Version
      id: get_version
      uses: battila7/get-version-action@v2
  
  build:
    needs: [version, get-version]
    runs-on: ubuntu-22.04
    steps:
    - name: Step único
      run: |
        echo 'Step único'
        echo "var1: ${{ needs.version.outputs.var1 }}"
        echo "var2: ${{ needs.version.outputs.var2 }}"
        echo "var3: ${{ needs.version.outputs.var3 }}"
        echo "version: ${{ needs.get-version.outputs.version }}"
        echo "version-without-v: ${{ needs.get-version.outputs.version-without-v }}"

  test:
    needs: [version, build]
    runs-on: ubuntu-22.04
    steps:
    - name: Step único
      run: |
        echo 'Step único'
        echo "var1: ${{ needs.version.outputs.var1 }}"
        echo "var2: ${{ needs.version.outputs.var2 }}"
        echo "var3: ${{ needs.version.outputs.var3 }}"

  pack:
    needs: [version, test]
    runs-on: ubuntu-22.04
    steps:
    - name: Step único
      run: |
        echo 'Step único'
        echo "var1: ${{ needs.version.outputs.var1 }}"
        echo "var2: ${{ needs.version.outputs.var2 }}"
        echo "var3: ${{ needs.version.outputs.var3 }}"

  publish:
    needs: [version, pack]
    runs-on: ubuntu-22.04
    steps:
    - name: Step único
      run: |
        echo 'Step único'
        echo "var1: ${{ needs.version.outputs.var1 }}"
        echo "var2: ${{ needs.version.outputs.var2 }}"
        echo "var3: ${{ needs.version.outputs.var3 }}"
